// General actions
export const INITIALIZE_PENDING = 'INITIALIZE_PENDING';
export const INITIALIZE_RESOLVED = 'INITIALIZE_RESOLVED';
export const INITIALIZE_REJECTED = 'INITIALIZE_REJECTED';

// Posts actions
export const GET_POSTS_LIST_PENDING = 'GET_POSTS_LIST_PENDING';
export const GET_POSTS_LIST_RESOLVED = 'GET_POSTS_LIST_RESOLVED';
export const GET_POSTS_LIST_REJECTED = 'GET_POSTS_LIST_REJECTED';

// Likes actions
export const LIKE_POST_PENDING = 'LIKE_POST_PENDING';
export const LIKE_POST_RESOLVED = 'LIKE_POST_RESOLVED';
export const LIKE_POST_REJECTED = 'LIKE_POST_REJECTED';

// Comments actions
export const ADD_COMMENT_PENDING = 'ADD_COMMENT_PENDING';
export const ADD_COMMENT_RESOLVED = 'ADD_COMMENT_RESOLVED';
export const ADD_COMMENT_REJECTED = 'ADD_COMMENT_REJECTED';
