// General actions
export const INITIALIZE_PENDING = 'INITIALIZE_PENDING';
export const INITIALIZE_RESOLVED = 'INITIALIZE_RESOLVED';
export const INITIALIZE_REJECTED = 'INITIALIZE_REJECTED';

// Users actions
export const GET_USERS_LIST_PENDING = 'GET_USERS_LIST_PENDING';
export const GET_USERS_LIST_RESOLVED = 'GET_USERS_LIST_RESOLVED';
export const GET_USERS_LIST_REJECTED = 'GET_USERS_LIST_REJECTED';

// Posts actions
export const GET_POSTS_LIST_PENDING = 'GET_POSTS_LIST_PENDING';
export const GET_POSTS_LIST_RESOLVED = 'GET_POSTS_LIST_RESOLVED';
export const GET_POSTS_LIST_REJECTED = 'GET_POSTS_LIST_REJECTED';

// Likes actions
export const LIKE_POST_PENDING = 'LIKE_POST_PENDING';
export const LIKE_POST_RESOLVED = 'LIKE_POST_RESOLVED';
export const LIKE_POST_REJECTED = 'LIKE_POST_REJECTED';

// Comments actions
export const GET_COMMENTS_LIST_PENDING = 'GET_COMMENTS_LIST_PENDING';
export const GET_COMMENTS_LIST_RESOLVED = 'GET_COMMENTS_LIST_RESOLVED';
export const GET_COMMENTS_LIST_REJECTED = 'GET_COMMENTS_LIST_REJECTED';
